name: ci-action

on:
  push:
    branches:
      - [master]
  pull_request:
    branches:
      - [develop]

jobs:
  build-and-test:
    if: ${{ !steps.skip-workflow.outputs.skip }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: yarn install
        run: yarn

      - name: run ESLint
        run: yarn lint
